export const PATH = {
  HOME: '/home',
  SIGNIN: '/auth/signin',
  POSTS: '/posts',
  PAYMENTS: '/payments',
  STATISTICS: '/statistics',
  USERS: '/users',
  FAVORITES: '/favorites',
  SETTINGS: '/settings',
  SEARCH: '/search',
  MESSENGER: '/messenger',
  MYPROFILE: '/profile',
  CREATE: '/create',
  PUBLIC: '/',
  USERS_LIST: '/userslist',
  PAYMENTS_LIST: '/paymentslist',
  POSTS_LIST: '/postslist',
}
