export const PATH = {
  HOME: '/home',
  SIGNIN: '/auth/signin',
  SIGNUP: '/auth/signup',
  NEW_PASSWORD: '/auth/create-new-password',
  FORGOTPASSWORD: '/auth/forgotpassword',
  REGISTRCONFIRMATION: '/auth/registration-confirmation',
  POSTS: '/posts',
  PAYMENTS: '/payments',
  STATISTICS: '/statistics',
  USERS: '/users',
  FAVORITES: '/favorites',
  SETTINGS: '/settings',
  SEARCH: '/search',
  MESSENGER: '/messenger',
  MYPROFILE: '/profile',
  CREATE: '/create',
  LINK_EXPIRED: '/auth/linkexpired',
  PUBLIC: '/',
  PRIVACY_POLICY: '/auth/privacypolicies',
  TERMS_OF_SERVICE: '/auth/termsofservice',
}
